from django.urls import path
from .views import *

urlpatterns = [
	path('',vista_index, name='index'),
    path('lista_videojuego/', vista_lista_videojuegos,name= 'videojuego'),
    path('lista_genero/', vista_lista_genero,name= 'genero'),
    path('lista_desarrollador/', vista_lista_desarrollador,name= 'desarrollador'),
    path('lista_distribuidor/', vista_lista_distribuidor,name= 'distribuidor'),
    path('lista_plataforma/', vista_lista_plataforma,name= 'plataforma'),
    path('detalle_videojuego/<int:id_v>/', vista_detalle_videojuegos,name= 'videojuegos_detalle'),
    path('detalle_genero/<int:id_g>/', vista_detalle_genero,name= 'genero_detalle'),
    path('detalle_desarrollador/<int:id_des>/', vista_detalle_desarrollador,name= 'desarrollador_detalle'),
    path('detalle_distribuidor/<int:id_dis>/', vista_detalle_distribuidor,name= 'distribuidor_detalle'),
    path('detalle_plataforma/<int:id_pla>/', vista_detalle_plataforma,name= 'plataforma_detalle'),
    path('agregar_videojuego/', vista_agregar_videojuego,name= 'agregar_videojuego'),
    path('agregar_genero/', vista_agregar_genero,name= 'agregar_genero'),
    path('agregar_desarrollador/', vista_agregar_desarrollador,name= 'agregar_desarrollador'),
    path('agregar_distribuidor/', vista_agregar_distribuidor,name= 'agregar_distribuidor'),
    path('agregar_plataforma/', vista_agregar_plataforma,name= 'agregar_plataforma'),
    path('modificar_videojuego/<int:id_v>/', vista_modificar_videojuego,name= 'modificar_videojuego'),
    path('modificar_genero/<int:id_g>/', vista_modificar_genero,name= 'modificar_genero'),
    path('modificar_desarrollador/<int:id_des>/', vista_modificar_desarrollador,name= 'modificar_desarrollador'),
    path('modificar_distribuidor/<int:id_dis>/', vista_modificar_distribuidor,name= 'modificar_distribuidor'),
    path('modificar_plataforma/<int:id_pla>/', vista_modificar_plataforma,name= 'modificar_plataforma'),
    path('eliminar_videojuego/<int:id_v>/', vista_eliminar_videojuego,name= 'eliminar_videojuego'),
    path('eliminar_genero/<int:id_g>/', vista_eliminar_genero,name= 'eliminar_genero'),
    path('eliminar_desarrollador/<int:id_des>/', vista_eliminar_desarrollador,name= 'eliminar_desarrollador'),
    path('eliminar_distribuidor/<int:id_dis>/', vista_eliminar_distribuidor,name= 'eliminar_distribuidor'),
    path('eliminar_plataforma/<int:id_pla>/', vista_eliminar_plataforma,name= 'eliminar_plataforma'),
    path('login/', vista_login, name='login'),
    path('logout/', vista_logout, name='logout'),
    path('registrar/', vista_registro, name='registrar'),
    
]